language: python
python:
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install pytest pytest-cov
install:
  - pip install -r requirements.txt
script: 
  - python Movie-Recommender.py  # run tests
  
after_success:
  - coverage run Movie-Recommender.py
  - pytest --cov=./
  - codecov # submit coverage
